global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:4000']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3002']

  - job_name: 'playlist-service'
    static_configs:
      - targets: ['playlist-service:3003']

  - job_name: 'analysis-service'
    static_configs:
      - targets: ['analysis-service:3001']
